(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"HEFT -- Higgs Effective Field Theory (LO + selectable NLO/NNLO operators)",
  Authors -> {"M. Ryczkowski"},
  Version -> "1",
  Date -> "02. 07. 2025",
  Description -> "Modular HEFT model: SM at LO with HEFT modifications (kappa, F-functions in H/vev). Selectable NLO/NNLO operators. Configuration: HEFTMaxOrder, HiggsMaxOrder. Bookkeepers: ChiralOrder (LO=0, NLO=1, NNLO=2), LamF, LamGold, LamHEFT. Notation follows Brivio et al. (arXiv:1604.06801)."};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {ExpansionF, 0}, {ExpansionChiral, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*2^(1/4)*Sqrt[Gf]*Kappa3H*MH^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*Sqrt[2]*Gf*Kappa4H*MH^2, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc3*IndexDelta[e1x2, e2x2], 0}, {I*gc3*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc4*IndexDelta[e1x2, e2x2], 0}, {I*gc4*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc5*IndexDelta[e1x2, e2x2], 0}, {I*gc5*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{2*aS*gc6*thetaS*SUNF[e1x2, e2x2, e3x2], 0}, {2*aS*gc6*thetaS*SUNF[e1x2, e2x2, e3x2], 0}, {2*aS*gc6*thetaS*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc6*Pi*SUNF[e1x2, e2x2, e3x2]), 0}, {gc6*Pi*SUNF[e1x2, e2x2, e3x2], 0}, {gc6*Pi*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc6*Pi*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc6*Pi*SUNF[e1x2, e2x2, e3x2]), 0}, {gc6*Pi*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(2*I)*aS*gc7*thetaS*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*gc7*Pi*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc7*Pi*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc7*Pi*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc9*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc9*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc9*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc11*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc12*SUNF[e1x2, e2x2, e3x2]), 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc12*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc12*SUNF[e1x2, e2x2, e3x2]), 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc13*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc13*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc13*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc14L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc14R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc15L[e1x2, e2x2], 0}, {I*gc15R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc16L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc16R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*gc17, 0}, {I*gc17, 0}, {I*gc17, 0}, {(-I)*gc17, 0}, {(-I)*gc17, 0}, {I*gc17, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc18, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc19, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc20, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{0, 0}, {(-I)*gc21, 0}, {(-I)*gc21, 0}, {(2*I)*gc21, 0}},

C[ V[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*gc22, 0}, {I*gc22, 0}, {I*gc22, 0}, {(-I)*gc22, 0}, {(-I)*gc22, 0}, {I*gc22, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{0, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(2*I)*gc23, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{0, 0}, {(-2*I)*gc24, 0}, {I*gc24, 0}, {I*gc24, 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc25, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc26, 0}},

C[ S[1] , S[1] , S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc27, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{0, 0}, {(-I)*gc28, 0}, {(-I)*gc28, 0}, {(2*I)*gc28, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc29*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc29*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc30L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc30R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc31[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc32[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc34L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc34R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc35*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc36*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc37*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc38*IndexDelta[e1x2, e2x2], 0}, {I*gc38*IndexDelta[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc39L*IndexDelta[e1x2, e2x2], 0}, {I*gc39R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc40*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc40*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc41*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc41*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> 2^(1/4)*CGHNLOn1*ChiralOrder*Sqrt[Gf],
     gc4 -> 2*Sqrt[2]*CGHNLOn2*ChiralOrder*Gf,
     gc5 -> 6*2^(3/4)*CGHNLOn3*ChiralOrder*Gf^(3/2),
     gc6 -> (-2*Sqrt[aS])/Sqrt[Pi],
     gc7 -> -4*aS,
     gc8 -> -12*2^(3/4)*Sqrt[aS]*CGHNLOn3*ChiralOrder*Gf^(3/2)*Sqrt[Pi],
     gc9 -> -24*2^(3/4)*aS*CGHNLOn3*ChiralOrder*Gf^(3/2)*Pi,
     gc10 -> -4*Sqrt[aS]*CGHNLOn2*ChiralOrder*Gf*Sqrt[2*Pi],
     gc11 -> -8*Sqrt[2]*aS*CGHNLOn2*ChiralOrder*Gf*Pi,
     gc12 -> -2*2^(1/4)*Sqrt[aS]*CGHNLOn1*ChiralOrder*Sqrt[Gf]*Sqrt[Pi],
     gc13 -> -4*2^(1/4)*aS*CGHNLOn1*ChiralOrder*Sqrt[Gf]*Pi,
     gc14L[e1x2_, e2x2_] -> -(Conjugate[ydH[e2x2, e1x2]]/Sqrt[2]),
     gc14R[e1x2_, e2x2_] -> -(ydH[e1x2, e2x2]/Sqrt[2]),
     gc15L[e1x2_, e2x2_] -> -(Conjugate[ylH[e2x2, e1x2]]/Sqrt[2]),
     gc15R[e1x2_, e2x2_] -> -(ylH[e1x2, e2x2]/Sqrt[2]),
     gc16L[e1x2_, e2x2_] -> -(Conjugate[yuH[e2x2, e1x2]]/Sqrt[2]),
     gc16R[e1x2_, e2x2_] -> -(yuH[e1x2, e2x2]/Sqrt[2]),
     gc17 -> (2^(1/4)*Sqrt[MZ*(Gf*MZ - Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])])/Sqrt[Gf*MZ^2],
     gc18 -> (-3*2^(1/4)*CFCn3*Sqrt[Gf]*MZ*(Sqrt[2]*(-1 + 2*CFTn0*ChiralOrder)*Gf^2*MZ^3 - 4*aEWM*(-1 + CFTn0*ChiralOrder)*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + 2*CFTn0*ChiralOrder)*Gf*MZ*(-4*aEWM*Pi + Sqrt[2]*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi),
     gc19 -> -((Kappa2V*MZ*(Sqrt[2]*(-1 + 2*CFTn0*ChiralOrder)*Gf^2*MZ^3 - 4*aEWM*(-1 + CFTn0*ChiralOrder)*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + 2*CFTn0*ChiralOrder)*Gf*MZ*(-4*aEWM*Pi + Sqrt[2]*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)),
     gc20 -> (2^(1/4)*KappaV*MZ*((1 - 2*CFTn0*ChiralOrder)*Gf^2*MZ^3 + 2*Sqrt[2]*aEWM*(-1 + CFTn0*ChiralOrder)*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + 2*CFTn0*ChiralOrder)*Gf*MZ*(2*Sqrt[2]*aEWM*Pi - MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Sqrt[Gf]*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)),
     gc21 -> -4*aEWM*Pi,
     gc22 -> -((2^(1/4)*MZ*((-1 + CFTn0*ChiralOrder)*Gf^2*MZ^3 + 2*Sqrt[2]*aEWM*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + CFTn0*ChiralOrder)*Gf*MZ*(-2*Sqrt[2]*aEWM*Pi + MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Sqrt[Gf*MZ^2]*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi))),
     gc23 -> (-2*MZ*(Sqrt[2]*(-1 + 2*CFTn0*ChiralOrder)*Gf^2*MZ^3 - 4*aEWM*(-1 + CFTn0*ChiralOrder)*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + 2*CFTn0*ChiralOrder)*Gf*MZ*(-4*aEWM*Pi + Sqrt[2]*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi),
     gc24 -> -((Sqrt[MZ*(Gf*MZ - Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*(Sqrt[2]*(-1 + CFTn0*ChiralOrder)*Gf^2*MZ^3 + 4*aEWM*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + CFTn0*ChiralOrder)*Gf*MZ*(-4*aEWM*Pi + Sqrt[2]*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Gf*MZ*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi))),
     gc25 -> 2*2^(1/4)*Sqrt[Gf]*(CFTn1*ChiralOrder + KappaV - 2*CFTn0*ChiralOrder*KappaV)*MZ^2,
     gc26 -> 2*Sqrt[2]*Gf*(2*CFTn2*ChiralOrder + Kappa2V - 2*CFTn0*ChiralOrder*Kappa2V)*MZ^2,
     gc27 -> 6*2^(3/4)*(CFCn3 - 2*CFCn3*CFTn0*ChiralOrder + 2*CFTn3*ChiralOrder)*Gf^(3/2)*MZ^2,
     gc28 -> (2*(Sqrt[2]*(-1 + 2*CFTn0*ChiralOrder)*Gf^2*MZ^4 - 4*aEWM*Pi*(Sqrt[2]*aEWM*Pi + (-1 + CFTn0*ChiralOrder)*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]) + Gf*MZ^2*(aEWM*(6 - 8*CFTn0*ChiralOrder)*Pi + Sqrt[2]*(-1 + 2*CFTn0*ChiralOrder)*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi),
     gc29 -> (2*2^(1/4)*Sqrt[MZ*(Gf*MZ - Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])])/(3*Sqrt[Gf*MZ^2]),
     gc30L -> (2^(1/4)*MZ*((1 - CFTn0*ChiralOrder)*Gf^2*MZ^3 - 4*Sqrt[2]*aEWM*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + 2*(-1 + CFTn0*ChiralOrder)*Gf*MZ*(Sqrt[2]*aEWM*Pi - MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(3*Sqrt[Gf*MZ^2]*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)),
     gc30R -> (-2*2^(1/4)*MZ*((1 - CFTn0*ChiralOrder)*Gf^2*MZ^3 + 2*Sqrt[2]*aEWM*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + CFTn0*ChiralOrder)*Gf*MZ*(2*Sqrt[2]*aEWM*Pi + MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(3*Sqrt[Gf*MZ^2]*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)),
     gc31[e1x2_, e2x2_] -> (Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*(Sqrt[2]*(-2 + CFTn0*ChiralOrder)*Gf^2*MZ^4 + 4*aEWM*Pi*(2*Sqrt[2]*aEWM*(-2 + CFTn0*ChiralOrder)*Pi - CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]) + Gf*MZ^2*(-8*aEWM*(-2 + CFTn0*ChiralOrder)*Pi + Sqrt[2]*CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]))*CKM[e1x2, e2x2])/(2^(3/4)*(Sqrt[2]*Gf*MZ^2 - 4*aEWM*Pi)*(-(Gf*MZ^2) + 2*Sqrt[2]*aEWM*Pi)),
     gc32[e1x2_, e2x2_] -> (Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*(Sqrt[2]*(-2 + CFTn0*ChiralOrder)*Gf^2*MZ^4 + 4*aEWM*Pi*(2*Sqrt[2]*aEWM*(-2 + CFTn0*ChiralOrder)*Pi - CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]) + Gf*MZ^2*(-8*aEWM*(-2 + CFTn0*ChiralOrder)*Pi + Sqrt[2]*CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]))*Conjugate[CKM[e2x2, e1x2]])/(2^(3/4)*(Sqrt[2]*Gf*MZ^2 - 4*aEWM*Pi)*(-(Gf*MZ^2) + 2*Sqrt[2]*aEWM*Pi)),
     gc33 -> -1/3*(2^(1/4)*Sqrt[MZ*(Gf*MZ - Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])])/Sqrt[Gf*MZ^2],
     gc34L -> (2^(1/4)*MZ*(2*(-1 + CFTn0*ChiralOrder)*Gf^2*MZ^3 + 2*Sqrt[2]*aEWM*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + CFTn0*ChiralOrder)*Gf*MZ*(-4*Sqrt[2]*aEWM*Pi + MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(3*Sqrt[Gf*MZ^2]*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)),
     gc34R -> (2^(1/4)*MZ*((1 - CFTn0*ChiralOrder)*Gf^2*MZ^3 + 2*Sqrt[2]*aEWM*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + CFTn0*ChiralOrder)*Gf*MZ*(2*Sqrt[2]*aEWM*Pi + MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(3*Sqrt[Gf*MZ^2]*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)),
     gc35 -> -(2^(1/4)*(-1 + CFTn0*ChiralOrder)*Sqrt[Gf*MZ^2]),
     gc36 -> (Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*(Sqrt[2]*(-2 + CFTn0*ChiralOrder)*Gf^2*MZ^4 + 4*aEWM*Pi*(2*Sqrt[2]*aEWM*(-2 + CFTn0*ChiralOrder)*Pi - CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]) + Gf*MZ^2*(-8*aEWM*(-2 + CFTn0*ChiralOrder)*Pi + Sqrt[2]*CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(2^(3/4)*(Sqrt[2]*Gf*MZ^2 - 4*aEWM*Pi)*(-(Gf*MZ^2) + 2*Sqrt[2]*aEWM*Pi)),
     gc37 -> (Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*(Sqrt[2]*(-2 + CFTn0*ChiralOrder)*Gf^2*MZ^4 + 4*aEWM*Pi*(2*Sqrt[2]*aEWM*(-2 + CFTn0*ChiralOrder)*Pi - CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]) + Gf*MZ^2*(-8*aEWM*(-2 + CFTn0*ChiralOrder)*Pi + Sqrt[2]*CFTn0*ChiralOrder*MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(2^(3/4)*(Sqrt[2]*Gf*MZ^2 - 4*aEWM*Pi)*(-(Gf*MZ^2) + 2*Sqrt[2]*aEWM*Pi)),
     gc38 -> -((2^(1/4)*Sqrt[MZ*(Gf*MZ - Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])]*Sqrt[MZ*(Gf*MZ + Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])])/Sqrt[Gf*MZ^2]),
     gc39L -> (2^(1/4)*Gf*MZ*((-1 + CFTn0*ChiralOrder)*Gf*MZ^2 + 2*Sqrt[2]*aEWM*Pi))/(Sqrt[Gf*MZ^2]*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)]),
     gc39R -> (2^(1/4)*MZ*((1 - CFTn0*ChiralOrder)*Gf^2*MZ^3 + 2*Sqrt[2]*aEWM*Pi*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)] + (-1 + CFTn0*ChiralOrder)*Gf*MZ*(2*Sqrt[2]*aEWM*Pi + MZ*Sqrt[Gf*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)])))/(Sqrt[Gf*MZ^2]*(Gf*MZ^2 - 2*Sqrt[2]*aEWM*Pi)),
     gc40 -> 2*Sqrt[aS]*Sqrt[Pi],
     gc41 -> 2*Sqrt[aS]*Sqrt[Pi]};

