(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"HEFT -- Higgs Effective Field Theory (LO + selectable NLO/NNLO operators)",
  Authors -> {"M. Ryczkowski"},
  Version -> "1",
  Date -> "02. 07. 2025",
  Description -> "Modular HEFT model: SM at LO with HEFT modifications (kappa, F-functions in H/vev). Selectable NLO/NNLO operators. Configuration: HEFTMaxOrder, HiggsMaxOrder. Bookkeepers: ChiralOrder (LO=0, NLO=1, NNLO=2), LamF, LamGold, LamHEFT. Notation follows Brivio et al. (arXiv:1604.06801)."};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {ExpansionF, 0}, {ExpansionChiral, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*hlambda*Kappa4H, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*hlambda*Kappa3H*vev, 0}},

C[ S[1] , S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc3*IndexDelta[e1x2, e2x2], 0}, {I*gc3*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc4*IndexDelta[e1x2, e2x2], 0}, {I*gc4*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc5*IndexDelta[e1x2, e2x2], 0}, {I*gc5*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{gc6*GS^2*thetaS*SUNF[e1x2, e2x2, e3x2], 0}, {gc6*GS^2*thetaS*SUNF[e1x2, e2x2, e3x2], 0}, {gc6*GS^2*thetaS*SUNF[e1x2, e2x2, e3x2], 0}, {-2*gc6*Pi^2*SUNF[e1x2, e2x2, e3x2], 0}, {2*gc6*Pi^2*SUNF[e1x2, e2x2, e3x2], 0}, {2*gc6*Pi^2*SUNF[e1x2, e2x2, e3x2], 0}, {-2*gc6*Pi^2*SUNF[e1x2, e2x2, e3x2], 0}, {-2*gc6*Pi^2*SUNF[e1x2, e2x2, e3x2], 0}, {2*gc6*Pi^2*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{I*gc7*GS^2*thetaS*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-2*I)*gc7*Pi^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(2*I)*gc7*Pi^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(2*I)*gc7*Pi^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc9*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc9*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc9*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc10*SUNF[e1x2, e2x2, e3x2]), 0}, {gc10*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc11*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc11*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc12*SUNF[e1x2, e2x2, e3x2]), 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc12*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc12*SUNF[e1x2, e2x2, e3x2]), 0}, {gc12*SUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc13*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc13*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc13*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc14L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc14R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc15L[e1x2, e2x2], 0}, {I*gc15R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc16L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc16R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*gc17, 0}, {I*gc17, 0}, {I*gc17, 0}, {(-I)*gc17, 0}, {(-I)*gc17, 0}, {I*gc17, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc18, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc19, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc20, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{0, 0}, {(-I)*gc21, 0}, {(-I)*gc21, 0}, {(2*I)*gc21, 0}},

C[ V[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {(-I)*gc22, 0}, {I*gc22, 0}, {I*gc22, 0}, {(-I)*gc22, 0}, {(-I)*gc22, 0}, {I*gc22, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{0, 0}, {(-I)*gc23, 0}, {(-I)*gc23, 0}, {(2*I)*gc23, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{0, 0}, {(-2*I)*gc24, 0}, {I*gc24, 0}, {I*gc24, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc25, 0}},

C[ S[1] , S[1] , S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc26, 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc27, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{0, 0}, {(-I)*gc28, 0}, {(-I)*gc28, 0}, {(2*I)*gc28, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc29*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc29*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc30L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc30R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc31[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc32[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc34L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc34R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc35*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc36*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc37*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc38*IndexDelta[e1x2, e2x2], 0}, {I*gc38*IndexDelta[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc39L*IndexDelta[e1x2, e2x2], 0}, {I*gc39R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc40*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc40*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc41*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc41*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> (6*CGHNLOn3*ChiralOrder)/vev^3,
     gc4 -> (2*CGHNLOn2*ChiralOrder)/vev^2,
     gc5 -> (CGHNLOn1*ChiralOrder)/vev,
     gc6 -> -1/2*GS/Pi^2,
     gc7 -> -1/2*GS^2/Pi^2,
     gc8 -> (-6*CGHNLOn3*ChiralOrder*GS)/vev^3,
     gc9 -> (-6*CGHNLOn3*ChiralOrder*GS^2)/vev^3,
     gc10 -> (-2*CGHNLOn2*ChiralOrder*GS)/vev^2,
     gc11 -> (-2*CGHNLOn2*ChiralOrder*GS^2)/vev^2,
     gc12 -> -((CGHNLOn1*ChiralOrder*GS)/vev),
     gc13 -> -((CGHNLOn1*ChiralOrder*GS^2)/vev),
     gc14L[e1x2_, e2x2_] -> -(Conjugate[ydH[e2x2, e1x2]]/Sqrt[2]),
     gc14R[e1x2_, e2x2_] -> -(ydH[e1x2, e2x2]/Sqrt[2]),
     gc15L[e1x2_, e2x2_] -> -(Conjugate[ylH[e2x2, e1x2]]/Sqrt[2]),
     gc15R[e1x2_, e2x2_] -> -(ylH[e1x2, e2x2]/Sqrt[2]),
     gc16L[e1x2_, e2x2_] -> -(Conjugate[yuH[e2x2, e1x2]]/Sqrt[2]),
     gc16R[e1x2_, e2x2_] -> -(yuH[e1x2, e2x2]/Sqrt[2]),
     gc17 -> (G1*GW)/Sqrt[G1^2 + GW^2],
     gc18 -> (GW^2*Kappa2V)/2,
     gc19 -> (3*CFCn3*GW^2)/(2*vev),
     gc20 -> (GW^2*KappaV*vev)/2,
     gc21 -> -((G1^2*GW^2)/(G1^2 + GW^2)),
     gc22 -> GW^2/Sqrt[G1^2 + GW^2],
     gc23 -> GW^2,
     gc24 -> (G1*GW^3)/(G1^2 + GW^2),
     gc25 -> ((G1^2 + GW^2)*(2*CFTn2*ChiralOrder + Kappa2V))/2,
     gc26 -> (3*(CFCn3 + 2*CFTn3*ChiralOrder)*(G1^2 + GW^2))/(2*vev),
     gc27 -> ((G1^2 + GW^2)*(CFTn1*ChiralOrder + KappaV)*vev)/2,
     gc28 -> -(GW^4/(G1^2 + GW^2)),
     gc29 -> (2*G1*GW)/(3*Sqrt[G1^2 + GW^2]),
     gc30L -> (-G1^2 + 3*GW^2)/(6*Sqrt[G1^2 + GW^2]),
     gc30R -> (-2*G1^2)/(3*Sqrt[G1^2 + GW^2]),
     gc31[e1x2_, e2x2_] -> (GW*CKM[e1x2, e2x2])/Sqrt[2],
     gc32[e1x2_, e2x2_] -> (GW*Conjugate[CKM[e2x2, e1x2]])/Sqrt[2],
     gc33 -> -1/3*(G1*GW)/Sqrt[G1^2 + GW^2],
     gc34L -> (-G1^2 - 3*GW^2)/(6*Sqrt[G1^2 + GW^2]),
     gc34R -> G1^2/(3*Sqrt[G1^2 + GW^2]),
     gc35 -> Sqrt[G1^2 + GW^2]/2,
     gc36 -> GW/Sqrt[2],
     gc37 -> GW/Sqrt[2],
     gc38 -> -((G1*GW)/Sqrt[G1^2 + GW^2]),
     gc39L -> (G1^2 - GW^2)/(2*Sqrt[G1^2 + GW^2]),
     gc39R -> G1^2/Sqrt[G1^2 + GW^2],
     gc40 -> GS,
     gc41 -> GS};

